# Generated by Django 3.2.5 on 2021-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('skill_1', models.CharField(max_length=20)),
                ('skill_2', models.CharField(max_length=20)),
                ('skill_3', models.CharField(max_length=20)),
                ('skill_4', models.CharField(max_length=20)),
                ('skill_5', models.CharField(max_length=20)),
                ('hobbies_1', models.CharField(max_length=20)),
                ('hobbies_2', models.CharField(max_length=20)),
                ('hobbies_3', models.CharField(max_length=20)),
            ],
        ),
    ]
