# Generated by Django 3.2.5 on 2021-09-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='add',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email_id',
            new_name='con',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='hobbies_1',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='hobbies_2',
            new_name='ho1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='hobbies_3',
            new_name='ho2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='ho3',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='skill_1',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='skill_2',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='skill_3',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='skill_4',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='skill_5',
            new_name='zip',
        ),
    ]
